export const COMMON_EXPORT_COLUMNS = [
    "source_mailbox",
    "graph_message_id",
    "internet_message_id",
    "received_at",
    "attachment_id",
    "attachment_name",
    "property_name",
    "property_slug",
    "report_type",
    "report_title",
    "report_date",
    "ingest_run_id"
];
export const REPORT_COLUMN_MAP = {
    history_forecast_rows: [
        ...COMMON_EXPORT_COLUMNS,
        "business_date",
        "section",
        "day_of_week",
        "total_occ",
        "arrivals",
        "comp_rooms",
        "house_use_rooms",
        "deduct_indiv_rooms",
        "non_deduct_indiv_rooms",
        "deduct_group_rooms",
        "non_deduct_group_rooms",
        "occupancy_pct",
        "room_revenue",
        "average_rate",
        "departures",
        "day_use_rooms",
        "no_show_rooms",
        "ooo_rooms",
        "in_house_people"
    ],
    manager_flash_metric_rows: [
        ...COMMON_EXPORT_COLUMNS,
        "metric_name",
        "period",
        "metric_value"
    ],
    reservations_made_yesterday_rows: [
        ...COMMON_EXPORT_COLUMNS,
        "guest_name",
        "arrival_date",
        "departure_date",
        "persons",
        "rooms",
        "nights",
        "rate_amount",
        "rate_code",
        "market_code",
        "booking_user",
        "made_on_date",
        "company_group_note"
    ],
    zero_rate_room_rows: [
        ...COMMON_EXPORT_COLUMNS,
        "room_account_no",
        "guest_or_group_name",
        "persons",
        "rate_code",
        "block_code",
        "market_code",
        "arrival_date",
        "departure_date",
        "balance_amount",
        "room_type",
        "payment_method",
        "tax_code",
        "note"
    ],
    ar_detailed_aging_rows: [
        ...COMMON_EXPORT_COLUMNS,
        "account_name",
        "guest_name",
        "invoice_no",
        "folio_no",
        "post_date",
        "up_to_30",
        "days_31_60",
        "days_61_90",
        "days_91_120",
        "days_121_150",
        "days_151_plus",
        "total_amount"
    ],
    rate_change_rows: [
        ...COMMON_EXPORT_COLUMNS,
        "confirmation_no",
        "room_no",
        "guest_name",
        "account_kind",
        "company_or_agent",
        "old_rate_code",
        "new_rate_code",
        "old_rate_amount",
        "new_rate_amount",
        "block_code",
        "changed_by",
        "changed_at"
    ],
    all_night_audit_report_rows: [
        ...COMMON_EXPORT_COLUMNS,
        "report_name",
        "section",
        "row_kind",
        "date_value",
        "metric_name",
        "account_no",
        "guest_name",
        "group_name",
        "room_no",
        "arrival_date",
        "departure_date",
        "nights",
        "status",
        "rate_amount",
        "rate_plan",
        "room_type",
        "source",
        "guarantee_type",
        "user_name",
        "cancel_code",
        "cancel_date",
        "cancel_clock",
        "reference_no",
        "configured_rate",
        "guest_rate",
        "difference",
        "value_1",
        "value_2",
        "value_3",
        "value_4",
        "value_5",
        "value_6",
        "value_7",
        "value_8",
        "value_9",
        "value_10",
        "value_11",
        "value_12",
        "value_13",
        "value_14",
        "value_15",
        "value_16",
        "note"
    ],
    choice_audit_packet_rows: [
        ...COMMON_EXPORT_COLUMNS,
        "page_number",
        "report_name",
        "section",
        "row_kind",
        "line_text",
        "metric_name",
        "status",
        "account_number",
        "account_name",
        "guest_name",
        "room_number",
        "arrival_date",
        "departure_date",
        "nights",
        "rate_code",
        "guarantee_type",
        "source_code",
        "room_type",
        "cancel_code",
        "cancel_date",
        "cancel_clock",
        "posting_date",
        "posting_time",
        "user_id",
        "shift",
        "account_type",
        "reference_id",
        "comment",
        "amount",
        "adjustment_amount",
        "balance_amount",
        "transaction_code",
        "transaction_description",
        "value_1",
        "value_2",
        "value_3",
        "value_4",
        "value_5",
        "value_6",
        "value_7",
        "value_8",
        "value_9",
        "value_10",
        "value_11",
        "value_12",
        "value_13",
        "value_14",
        "value_15",
        "value_16",
        "note"
    ],
    best_western_daily_report_rows: [
        ...COMMON_EXPORT_COLUMNS,
        "section",
        "subsection",
        "group_name",
        "row_kind",
        "metric_name",
        "posting_code",
        "posting_description",
        "transaction_count",
        "today_value",
        "mtd_value",
        "last_year_mtd_value",
        "mtd_variance",
        "ytd_value",
        "last_year_ytd_value",
        "ytd_variance",
        "opening_balance",
        "debits",
        "credits",
        "closing_balance"
    ],
    adjustment_refund_activity_rows: [
        ...COMMON_EXPORT_COLUMNS,
        "section",
        "row_kind",
        "transaction_date",
        "transaction_time",
        "transaction_scope",
        "charge_type",
        "subject_name",
        "transaction_number",
        "room_number",
        "reason_code",
        "adjusted_amount",
        "adjusted_tax",
        "transferred_charge",
        "transferred_tax",
        "username",
        "remarks",
        "note"
    ],
    all_transaction_rows: [
        ...COMMON_EXPORT_COLUMNS,
        "section",
        "transaction_date",
        "transaction_time",
        "confirmation_no",
        "guest_name",
        "room_number",
        "folio_number",
        "transaction_code",
        "transaction_description",
        "last_four_digits",
        "transaction_type",
        "charge_type",
        "amount",
        "username",
        "note"
    ],
    room_tax_listing_rows: [
        ...COMMON_EXPORT_COLUMNS,
        "room_number",
        "guest_name",
        "confirmation_no",
        "charge_type",
        "arrival_date",
        "departure_date",
        "rate_amount",
        "override_flag",
        "tax_amount",
        "package_name",
        "extra_1",
        "extra_2",
        "transfer_flag",
        "payment_method"
    ],
    daily_transaction_log_rows: [
        ...COMMON_EXPORT_COLUMNS,
        "transaction_code",
        "transaction_description",
        "room_number",
        "transaction_id",
        "confirmation_no",
        "guest_name",
        "reference_value",
        "posted_amount",
        "adjusted_amount",
        "original_id",
        "original_date",
        "void_from_value",
        "clerk_name",
        "transaction_time"
    ],
    credit_card_transaction_rows: [
        ...COMMON_EXPORT_COLUMNS,
        "card_type",
        "card_number_fragment",
        "transaction_status",
        "payment_code",
        "room_number",
        "confirmation_no",
        "guest_name",
        "authorization_no",
        "batch_id",
        "charge_amount",
        "credit_amount",
        "transaction_id",
        "void_from_value",
        "clerk_name",
        "transaction_time"
    ],
    closed_folio_balance_rows: [
        ...COMMON_EXPORT_COLUMNS,
        "section",
        "row_kind",
        "summary_label",
        "confirmation_no",
        "group_code",
        "room_number",
        "guest_name",
        "additional_guests",
        "company_name",
        "check_in_date",
        "check_out_date",
        "rate_plan",
        "payment_method",
        "reservation_status",
        "todays_charges",
        "todays_payments",
        "opening_balance",
        "net_change",
        "ending_balance",
        "metric_value",
        "note"
    ],
    operator_transaction_rows: [
        ...COMMON_EXPORT_COLUMNS,
        "transaction_code",
        "transaction_description",
        "transaction_id",
        "confirmation_no",
        "guest_name",
        "reference_value",
        "amount",
        "adjustment_amount",
        "original_id",
        "original_date",
        "void_from_value",
        "clerk_name",
        "transaction_time"
    ],
    advance_deposit_activity_rows: [
        ...COMMON_EXPORT_COLUMNS,
        "confirmation_no",
        "guest_name",
        "check_in_date",
        "rate_plan_name",
        "payment_method",
        "due_date",
        "deposit_posted"
    ],
    booked_reservations_rows: [
        ...COMMON_EXPORT_COLUMNS,
        "booking_date",
        "confirmation_no",
        "guest_name",
        "company_name",
        "arrival_date",
        "nights",
        "rate_plan",
        "total_room_rate",
        "adr",
        "booked_by",
        "guarantee_method"
    ],
    direct_bill_aging_rows: [
        ...COMMON_EXPORT_COLUMNS,
        "section",
        "company_name",
        "company_code",
        "current_amount",
        "over_30_amount",
        "over_60_amount",
        "over_90_amount",
        "over_120_amount",
        "over_150_amount",
        "total_amount"
    ],
    direct_bill_ledger_rows: [
        ...COMMON_EXPORT_COLUMNS,
        "company_name",
        "confirmation_no",
        "guest_name",
        "check_in_date",
        "check_out_date",
        "current_amount",
        "over_7_amount",
        "over_14_amount",
        "over_30_amount",
        "over_60_amount",
        "over_90_amount",
        "over_120_days_amount",
        "over_150_amount",
        "total_amount"
    ],
    final_audit_metric_rows: [
        ...COMMON_EXPORT_COLUMNS,
        "section",
        "metric_name",
        "value_1",
        "value_2",
        "value_3",
        "value_4",
        "value_5",
        "value_6",
        "value_7",
        "value_8",
        "value_9",
        "value_10"
    ],
    high_balance_report_rows: [
        ...COMMON_EXPORT_COLUMNS,
        "room_number",
        "guest_name",
        "guest_tier",
        "arrival_date",
        "departure_date",
        "room_rate",
        "folio_name",
        "folio_balance",
        "credit_balance",
        "outstanding_balance",
        "payment_method",
        "available_credit_limit",
        "auto_top_off_status"
    ],
    hotel_statistics_metric_rows: [
        ...COMMON_EXPORT_COLUMNS,
        "section",
        "metric_name",
        "value_1",
        "value_2",
        "value_3",
        "value_4",
        "value_5"
    ],
    in_house_guest_folio_balance_rows: [
        ...COMMON_EXPORT_COLUMNS,
        "section",
        "row_kind",
        "summary_label",
        "confirmation_no",
        "group_code",
        "room_number",
        "guest_name",
        "additional_guests",
        "company_name",
        "check_in_date",
        "check_out_date",
        "rate_plan",
        "payment_method",
        "reservation_status",
        "todays_charges",
        "todays_payments",
        "opening_balance",
        "net_change",
        "ending_balance",
        "metric_value",
        "note"
    ],
    maintenance_summary_rows: [
        ...COMMON_EXPORT_COLUMNS,
        "business_date",
        "day_of_week",
        "maintenance_type",
        "reason",
        "open_issues",
        "closed_issues",
        "cancelled_issues"
    ],
    occupancy_forecast_rows: [
        ...COMMON_EXPORT_COLUMNS,
        "business_date",
        "day_of_week",
        "group_confirmed_revenue",
        "transient_confirmed_revenue",
        "total_confirmed_revenue",
        "allocation_revenue",
        "total_available_revenue",
        "total_rooms",
        "ooo_rooms",
        "available_rooms",
        "arrivals",
        "stay_overs",
        "departures"
    ],
    rate_override_rows: [
        ...COMMON_EXPORT_COLUMNS,
        "modification_date",
        "stay_date",
        "modification_time",
        "confirmation_no",
        "check_in_date",
        "check_out_date",
        "guest_name",
        "stay_nights",
        "room_type",
        "sold_rate",
        "new_rate",
        "rate_plan",
        "override_amount",
        "username",
        "reason"
    ],
    rate_report_rows: [
        ...COMMON_EXPORT_COLUMNS,
        "room_number",
        "room_type",
        "guest_name",
        "adults",
        "children",
        "reservation_status",
        "nights",
        "check_in_date",
        "check_out_date",
        "room_rate",
        "room_fees",
        "total_guest_balance",
        "note"
    ],
    reservation_listing_rows: [
        ...COMMON_EXPORT_COLUMNS,
        "section",
        "row_kind",
        "summary_label",
        "market_segment_code",
        "local_segment_code",
        "confirmation_no",
        "group_number",
        "group_code",
        "external_confirmation_no",
        "external_cancellation_no",
        "po_number",
        "ota_booking_number",
        "package_number",
        "note"
    ],
    tax_report_rows: [
        ...COMMON_EXPORT_COLUMNS,
        "section",
        "tax_name",
        "total_revenue",
        "exempted_revenue",
        "taxable_payable",
        "payable_tax",
        "exempted_tax",
        "transaction_number",
        "folio_number",
        "transaction_type",
        "room_number",
        "guest_name",
        "company_name",
        "check_in_date",
        "check_out_date",
        "exemption_category",
        "revenue"
    ],
    trial_balance_report_rows: [
        ...COMMON_EXPORT_COLUMNS,
        "row_kind",
        "account_type",
        "account_name",
        "transaction_code",
        "opening_balance",
        "debit_amount",
        "credit_amount",
        "net_change",
        "closing_balance",
        "note"
    ]
};
export const REPORT_EXPORT_COLUMN_MAP = Object.fromEntries(Object.entries(REPORT_COLUMN_MAP).map(([reportType, columns]) => [
    reportType,
    columns.filter((column) => !COMMON_EXPORT_COLUMNS.includes(column))
]));
export const REPORT_TITLES = {
    history_forecast_rows: "History and Forecast",
    manager_flash_metric_rows: "Manager - Flash Last Day",
    reservations_made_yesterday_rows: "Reservations - made Yesterday",
    zero_rate_room_rows: "Zero Rate Rooms",
    ar_detailed_aging_rows: "AR Detailed Aging",
    rate_change_rows: "Rate Change Report",
    all_night_audit_report_rows: "All Night Audit Reports",
    choice_audit_packet_rows: "Daily Audit Packet",
    best_western_daily_report_rows: "Daily Report",
    adjustment_refund_activity_rows: "Adjustments and Refunds Activity",
    all_transaction_rows: "All Transactions",
    room_tax_listing_rows: "Room & Tax Listing",
    daily_transaction_log_rows: "Daily Transaction Log",
    credit_card_transaction_rows: "Credit Card Transactions",
    closed_folio_balance_rows: "Closed Folio Balances",
    operator_transaction_rows: "Operator Transactions",
    advance_deposit_activity_rows: "Advance Deposit Activity",
    booked_reservations_rows: "Booked Reservations",
    direct_bill_aging_rows: "Direct Bill Aging",
    direct_bill_ledger_rows: "Direct Bill Ledger Details",
    final_audit_metric_rows: "Final Audit",
    high_balance_report_rows: "High Balance Report",
    hotel_statistics_metric_rows: "Hotel Statistics",
    in_house_guest_folio_balance_rows: "In House Guest Folio Balances",
    maintenance_summary_rows: "Maintenance Summary",
    occupancy_forecast_rows: "Occupancy Forecast",
    rate_override_rows: "Rate Override",
    rate_report_rows: "Rate Report",
    reservation_listing_rows: "Reservations",
    tax_report_rows: "Tax Report",
    trial_balance_report_rows: "Trial Balance Report"
};
