import type { ReportType } from "./types.js";

export const COMMON_EXPORT_COLUMNS = [
  "source_mailbox",
  "graph_message_id",
  "internet_message_id",
  "received_at",
  "attachment_id",
  "attachment_name",
  "property_name",
  "property_slug",
  "report_type",
  "report_title",
  "report_date",
  "ingest_run_id"
] as const;

export const REPORT_COLUMN_MAP: Record<ReportType, readonly string[]> = {
  history_forecast_rows: [
    ...COMMON_EXPORT_COLUMNS,
    "business_date",
    "section",
    "day_of_week",
    "total_occ",
    "arrivals",
    "comp_rooms",
    "house_use_rooms",
    "deduct_indiv_rooms",
    "non_deduct_indiv_rooms",
    "deduct_group_rooms",
    "non_deduct_group_rooms",
    "occupancy_pct",
    "room_revenue",
    "average_rate",
    "departures",
    "day_use_rooms",
    "no_show_rooms",
    "ooo_rooms",
    "in_house_people"
  ],
  manager_flash_metric_rows: [
    ...COMMON_EXPORT_COLUMNS,
    "metric_name",
    "period",
    "metric_value"
  ],
  reservations_made_yesterday_rows: [
    ...COMMON_EXPORT_COLUMNS,
    "guest_name",
    "arrival_date",
    "departure_date",
    "persons",
    "rooms",
    "nights",
    "rate_amount",
    "rate_code",
    "market_code",
    "booking_user",
    "made_on_date",
    "company_group_note"
  ],
  zero_rate_room_rows: [
    ...COMMON_EXPORT_COLUMNS,
    "room_account_no",
    "guest_or_group_name",
    "persons",
    "rate_code",
    "block_code",
    "market_code",
    "arrival_date",
    "departure_date",
    "balance_amount",
    "room_type",
    "payment_method",
    "tax_code",
    "note"
  ],
  ar_detailed_aging_rows: [
    ...COMMON_EXPORT_COLUMNS,
    "account_name",
    "guest_name",
    "invoice_no",
    "folio_no",
    "post_date",
    "up_to_30",
    "days_31_60",
    "days_61_90",
    "days_91_120",
    "days_121_150",
    "days_151_plus",
    "total_amount"
  ],
  rate_change_rows: [
    ...COMMON_EXPORT_COLUMNS,
    "confirmation_no",
    "room_no",
    "guest_name",
    "account_kind",
    "company_or_agent",
    "old_rate_code",
    "new_rate_code",
    "old_rate_amount",
    "new_rate_amount",
    "block_code",
    "changed_by",
    "changed_at"
  ],
  all_night_audit_report_rows: [
    ...COMMON_EXPORT_COLUMNS,
    "report_name",
    "section",
    "row_kind",
    "date_value",
    "metric_name",
    "account_no",
    "guest_name",
    "group_name",
    "room_no",
    "arrival_date",
    "departure_date",
    "nights",
    "status",
    "rate_amount",
    "rate_plan",
    "room_type",
    "source",
    "guarantee_type",
    "user_name",
    "cancel_code",
    "cancel_date",
    "cancel_clock",
    "reference_no",
    "configured_rate",
    "guest_rate",
    "difference",
    "value_1",
    "value_2",
    "value_3",
    "value_4",
    "value_5",
    "value_6",
    "value_7",
    "value_8",
    "value_9",
    "value_10",
    "value_11",
    "value_12",
    "value_13",
    "value_14",
    "value_15",
    "value_16",
    "note"
  ],
  best_western_daily_report_rows: [
    ...COMMON_EXPORT_COLUMNS,
    "section",
    "subsection",
    "group_name",
    "row_kind",
    "metric_name",
    "posting_code",
    "posting_description",
    "transaction_count",
    "today_value",
    "mtd_value",
    "last_year_mtd_value",
    "mtd_variance",
    "ytd_value",
    "last_year_ytd_value",
    "ytd_variance",
    "opening_balance",
    "debits",
    "credits",
    "closing_balance"
  ],
  advance_deposit_activity_rows: [
    ...COMMON_EXPORT_COLUMNS,
    "confirmation_no",
    "guest_name",
    "check_in_date",
    "rate_plan_name",
    "payment_method",
    "due_date",
    "deposit_posted"
  ],
  booked_reservations_rows: [
    ...COMMON_EXPORT_COLUMNS,
    "booking_date",
    "confirmation_no",
    "guest_name",
    "company_name",
    "arrival_date",
    "nights",
    "rate_plan",
    "total_room_rate",
    "adr",
    "booked_by",
    "guarantee_method"
  ],
  direct_bill_aging_rows: [
    ...COMMON_EXPORT_COLUMNS,
    "section",
    "company_name",
    "company_code",
    "current_amount",
    "over_30_amount",
    "over_60_amount",
    "over_90_amount",
    "over_120_amount",
    "over_150_amount",
    "total_amount"
  ],
  direct_bill_ledger_rows: [
    ...COMMON_EXPORT_COLUMNS,
    "company_name",
    "confirmation_no",
    "guest_name",
    "check_in_date",
    "check_out_date",
    "current_amount",
    "over_7_amount",
    "over_14_amount",
    "over_30_amount",
    "over_60_amount",
    "over_90_amount",
    "over_120_days_amount",
    "over_150_amount",
    "total_amount"
  ],
  final_audit_metric_rows: [
    ...COMMON_EXPORT_COLUMNS,
    "section",
    "metric_name",
    "value_1",
    "value_2",
    "value_3",
    "value_4",
    "value_5",
    "value_6",
    "value_7",
    "value_8",
    "value_9",
    "value_10"
  ],
  high_balance_report_rows: [
    ...COMMON_EXPORT_COLUMNS,
    "room_number",
    "guest_name",
    "guest_tier",
    "arrival_date",
    "departure_date",
    "room_rate",
    "folio_name",
    "folio_balance",
    "credit_balance",
    "outstanding_balance",
    "payment_method",
    "available_credit_limit",
    "auto_top_off_status"
  ],
  hotel_statistics_metric_rows: [
    ...COMMON_EXPORT_COLUMNS,
    "section",
    "metric_name",
    "value_1",
    "value_2",
    "value_3",
    "value_4",
    "value_5"
  ],
  maintenance_summary_rows: [
    ...COMMON_EXPORT_COLUMNS,
    "business_date",
    "day_of_week",
    "maintenance_type",
    "reason",
    "open_issues",
    "closed_issues",
    "cancelled_issues"
  ],
  occupancy_forecast_rows: [
    ...COMMON_EXPORT_COLUMNS,
    "business_date",
    "day_of_week",
    "group_confirmed_revenue",
    "transient_confirmed_revenue",
    "total_confirmed_revenue",
    "allocation_revenue",
    "total_available_revenue",
    "total_rooms",
    "ooo_rooms",
    "available_rooms",
    "arrivals",
    "stay_overs",
    "departures"
  ],
  rate_override_rows: [
    ...COMMON_EXPORT_COLUMNS,
    "modification_date",
    "stay_date",
    "modification_time",
    "confirmation_no",
    "check_in_date",
    "check_out_date",
    "guest_name",
    "stay_nights",
    "room_type",
    "sold_rate",
    "new_rate",
    "rate_plan",
    "override_amount",
    "username",
    "reason"
  ],
  tax_report_rows: [
    ...COMMON_EXPORT_COLUMNS,
    "section",
    "tax_name",
    "total_revenue",
    "exempted_revenue",
    "taxable_payable",
    "payable_tax",
    "exempted_tax",
    "transaction_number",
    "folio_number",
    "transaction_type",
    "room_number",
    "guest_name",
    "company_name",
    "check_in_date",
    "check_out_date",
    "exemption_category",
    "revenue"
  ]
};

export const REPORT_TITLES: Record<ReportType, string> = {
  history_forecast_rows: "History and Forecast",
  manager_flash_metric_rows: "Manager - Flash Last Day",
  reservations_made_yesterday_rows: "Reservations - made Yesterday",
  zero_rate_room_rows: "Zero Rate Rooms",
  ar_detailed_aging_rows: "AR Detailed Aging",
  rate_change_rows: "Rate Change Report",
  all_night_audit_report_rows: "All Night Audit Reports",
  best_western_daily_report_rows: "Daily Report",
  advance_deposit_activity_rows: "Advance Deposit Activity",
  booked_reservations_rows: "Booked Reservations",
  direct_bill_aging_rows: "Direct Bill Aging",
  direct_bill_ledger_rows: "Direct Bill Ledger Details",
  final_audit_metric_rows: "Final Audit",
  high_balance_report_rows: "High Balance Report",
  hotel_statistics_metric_rows: "Hotel Statistics",
  maintenance_summary_rows: "Maintenance Summary",
  occupancy_forecast_rows: "Occupancy Forecast",
  rate_override_rows: "Rate Override",
  tax_report_rows: "Tax Report"
};
